### ISSUE TITLE
Issue with white spaces on files

### ISSUE THREAD

**Issue by adsanz** [kaltura/nginx-aws-auth-module#10]
Hi, I've been trying to use this module to show some private files vía nginx reverse proxy, some of this files give back this error

```
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
.....
```
It matches that those files have whitespaces on their names

Any plans on supporting whitespace filenames? Users can upload files via private area, and we don't have control over the names.

**Comment by adsanz** [comment]
I thought it might be useful mentioning, I'm using nginx 1.18.0 on Ubuntu 18.04, built the latest version of your module as a dynamic module, configuration is as stated on the readme and everything works except for those files

**Comment by kaltura-hooks** [comment]
Hi @adsanz,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment]
@adsanz, are you running on latest master? I pushed #9 few days ago, I think it was supposed to fix this issue.

**Comment by adsanz** [comment]
Yep, running on master latest commit is 

```
commit 4b385e4c1d65048884ec873c4c7bed45c29581cc (HEAD -> master, origin/master, origin/HEAD)
Merge: b6353cf f40c128
Author: erankor <eran.kornblau@kaltura.com>
Date:   Thu Dec 10 19:24:19 2020 +0200

    Merge pull request #9 from kaltura/escape-uri-components
    
    bug fix: escape each uri component

```

it works fine with files that add new elements to the uri like the itok=xxxx that drupal adds, and it works well with other encoded values like @ seems to be a specific issue with white spaces

**Comment by erankor** [comment]
Please try this pull #11, works for me with spaces ('+'), and also fixes a few other cases...
Only cases I'm aware of that are still not handled are '/./' and '/../'.

**Comment by adsanz** [comment]
Hello, 

I've tried locally and it works fine! Now images with whitespaces loads and also the rest of the statics loads a bit faster, don't know if that has something to do with the change or my test bench

Closing this issue since #11 works

**Comment by erankor** [comment]
Thanks, merged
