### ISSUE TITLE
SignatureDoesNot match issue when secret key starts with "/"

### ISSUE THREAD

**Issue by adsanz** [kaltura/nginx-aws-auth-module#12]
Hi again!

A while ago I opened an issue related to signature does not match errors on files which had white spaces, now is related to the secret key, or at least it looks like. I added a secret key that has a "/" as the first character, this caused a signature does not match error on all the files proxied with nginx.

This is quite a rare case, since access key are randomly generated, and it took me quite long to notice it.

Some info:
Nginx 1.18, docker image with module added statically, other keys with the exact same configuration works perfectly.

**Comment by kaltura-hooks** [comment]
Hi @adsanz,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment]
Sorry, but this doesn't make much sense to me... the only thing that is done with the secret key is to hash it with sha256, so it doesn't matter what characters are there. Also, we've been using this module with temporary (role based) tokens on our production environment for the past year or so, and haven't seen such issue.

**Comment by adsanz** [comment]
Well, I don't know if you can check that hash function adding a "/" character at the start of a secret key, I think it might be escaped or something before being hashed which could cause the signature error.

**Comment by erankor** [comment]
Maybe in the flow you generate it, you are getting it escaped while it shouldn't be (e.g. some JSON encoders escape / with \, some don't).
As I wrote above, we are generating temporary tokens every hour for the last year (that's at least 8k tokens), and haven't seen any issue (if S3 auth fails, it's something that cannot go unnoticed...). I'm assuming that if X% of the tokens happen to start with '/', we have received many tokens like that...
If you have a concrete example that you can share, I can check it out.

**Comment by adsanz** [comment]
Sorry for the late answer, quite busy these days...

There's no modification on the flow, I mean there's just a browser -> nginx -> private s3 statics. I would like to set a testing env for you, but I did removed those keys since they were not going to be used anymore. We can close the issue for now if I came across this error again, I'll prepare a nice testing environment for you guys to test it out.
