### ISSUE TITLE
Example of adding nginx-aws-auth-module to a Dockerfile

### ISSUE THREAD

**Issue by Rogier-blip** [kaltura/nginx-aws-auth-module#17]
Hee all,

Thanks for this library it is very helpful.

I have a question, do you have an example of how to add this module to a Dockefile?

Cheers

**Comment by kaltura-hooks** [comment]
Hi @Rogier-blip,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment]
You can use something like this as reference -
https://github.com/nytimes/nginx-vod-module-docker/blob/master/Dockerfile
It builds nginx with our nginx-vod-module, but you can easily change it to include this module instead + add any additional modules you may need.

**Comment by Rogier-blip** [comment]
Thanks will have a look! I'll post the result here for future reference!

**Comment by Rogier-blip** [comment]
@erankor I am running issue. 

I created the Dockerfile, but I get an error when running the image. With this error: `nginx: [emerg] unknown directive "aws_auth_presign" in /usr/local/nginx/conf/nginx.conf:9`

I created a repo that you can pull to reproduce the issue: https://github.com/Rogier-blip/nginx-aws-auth-module-test.

Any idea what this could be? I have the feeling it could be that I am missing some apk modules in the Dockerfile at line 5.

**Comment by erankor** [comment]
The commit you took doesn't have this feature... 
I've now tagged `1.1` from latest master, you can use it instead.

**Comment by Rogier-blip** [comment]
The Dockerfile with nginx-aws-auth-module can be found In this repo, https://github.com/Rogier-blip/nginx-aws-auth-module-test

**Comment by erankor** [comment]
btw, you can probably drop ffmpeg/ffmpeg-dev from the dockerfile

**Comment by Rogier-blip** [comment]
Thanks!
