### ISSUE TITLE
Question with apostrophe in path

### ISSUE THREAD

**Issue by DoctorFTB** [kaltura/nginx-aws-auth-module#21]
I have a file with an apostrophe "my'file.txt". I upload a file to my-bucket. I'm trying to use this module and getting an error with the calculated signature. Are there any ways why the error occurred?
And additional information: download works if I set "my%27file.txt"

![image](https://github.com/kaltura/nginx-aws-auth-module/assets/20482982/e953a509-57be-4d50-bb70-aedda2d6a8dd)

Thanks!

**Comment by erankor** [comment]
Hi, when building the "canonical request", as part of the signature calculation, the module escapes the single quote to %27, this follows the [AWS spec](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html) -
`URI encode every byte except the unreserved characters: 'A'-'Z', 'a'-'z', '0'-'9', '-', '.', '_', and '~'.`
However, the module does not alter the URI of the request - it only has control of the signature. So S3 gets a request for a request for the file containing the single quote, but signed with %27. It's weird that it doesn't work though, I'd expect S3 to escape the URI in the same way, and get the same signature...
Checking with AWS CLI, I see that it escapes the single quote on the URI -
```
$ aws s3 presign "s3://bucket-name/path'fdsaf"
https://bucket-name.s3.us-east-1.amazonaws.com/path%27fdsaf?X-Amz-Algorithm=AWS4-HMAC-SHA256&...
```
Since the module can't change the URI of the request, as I mentioned above, I don't think I have much to do about this, you'll probably have to escape it yourself.

**Comment by DoctorFTB** [comment]
I don’t know how I checked before, but after recompile module - its work! Sorry for my mistake. Previously (before tests) I used an old version of the module.
Thanks!
